apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    environment: pre-prod
    steps:
      - name: Deploy App4-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].digest }}
          target-environment: pre-prod
          name: App4-Frontend

      - name: Deploy App4-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].digest }}
          target-environment: pre-prod
          name: App4-Backend

      - name: Deploy App4-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].digest }}
          target-environment: pre-prod
          name: App4-APIs
  prod:
    needs: pre-prod
    environment: prod
    steps:
      - name: Deploy App4-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-Frontend']['App4-Frontend'].digest }}
          target-environment: prod
          name: App4-Frontend

      - name: Deploy App4-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-Backend']['App4-Backend'].digest }}
          target-environment: prod
          name: App4-Backend

      - name: Deploy App4-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App4-APIs']['App4-APIs'].digest }}
          target-environment: prod
          name: App4-APIs
